In [1]:
import pandas as pd
import numpy as np
with open('./outputfilename.csv') as f:
    df = pd.read_csv(f)

In [2]:
df.dropna(subset=['tagname'], inplace=True)
df = df.sort_values(['tagname', 'time'])
df = df.astype(str)
print(df['qdyyb'].value_counts())
print(df)

nan    1045295
0.0       1652
1.0       1628
Name: qdyyb, dtype: int64
                         tagname                 time               zxtyy  \
199700   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:01  146.46667480000002
458706   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:03         146.5999908
925427   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:04         146.3999939
100097   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:05  146.66667180000002
437888   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:07         146.5999908
422062   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:09  146.46667480000002
794625   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:10         146.5999908
427325   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:11  146.46667480000002
162982   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:12         146.5999908
5226     NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:13  146.46667480000002
84394    NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:14         146.5999908
300438   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:15         146.3999939
516247   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:16  146.46667480000002
993620   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:18         146.5999908
993621   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:20         146.3999939
888961   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:22  146.66667180000002
368964   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:23  146.46667480000002
395392   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:25  146.66667180000002
731403   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:26         146.5999908
453355   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:28         146.3999939
310821   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:29  146.66667180000002
721072   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:30         146.5999908
579413   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:31  146.46667480000002
100098   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:32         146.5999908
831453   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:33  146.46667480000002
705303   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:36  146.66667180000002
663380   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:37  146.46667480000002
652832   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:38         146.5999908
699981   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:40  146.46667480000002
384970   NX_GD_SBQF_FJ_P1_L1_001  2020-05-01 00:00:41         146.5999908
...                          ...                  ...                 ...
852402   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:47         140.4666595
1025432  NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:48         139.9333344
553162   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:49         139.7333374
873287   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:50  139.66667180000002
537269   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:51  139.33332819999998
47404    NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:52         139.1333313
1035955  NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:53         138.6000061
15635    NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:54  138.53332519999998
263249   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:55  138.33332819999998
157725   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:57         137.9333344
237016   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:47:59         137.8000031
820896   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:00  137.53332519999998
358479   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:04  137.33332819999998
967334   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:05         137.3999939
962072   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:06         137.1333313
173549   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:08         136.9333344
358480   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:12  136.73332209999998
73840    NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:14         136.6000061
741975   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:15  136.53332519999998
820897   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:17         136.3999939
479421   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:20  136.53332519999998
658046   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:21  136.33332819999998
568856   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:22         136.3999939
168253   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:23         136.1999969
5216     NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:25         136.1333313
411374   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:26         136.1999969
20909    NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:27         136.1333313
768255   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:28               136.0
568857   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:31         135.9333344
183970   NX_GD_SBQF_FJ_P1_L1_001  2020-05-23 05:48:32               136.0

        fksj qdyyb yldx ylgx gzsjgcgz djbhgz fjph
199700   nan   nan  nan  nan      nan    nan  nan
458706   nan   nan  nan  nan      nan    nan  nan
925427   nan   nan  nan  nan      nan    nan  nan
100097   nan   nan  nan  nan      nan    nan  nan
437888   nan   nan  nan  nan      nan    nan  nan
422062   nan   nan  nan  nan      nan    nan  nan
794625   nan   nan  nan  nan      nan    nan  nan
427325   nan   nan  nan  nan      nan    nan  nan
162982   nan   nan  nan  nan      nan    nan  nan
5226     nan   nan  nan  nan      nan    nan  nan
84394    nan   nan  nan  nan      nan    nan  nan
300438   nan   nan  nan  nan      nan    nan  nan
516247   nan   nan  nan  nan      nan    nan  nan
993620   nan   nan  nan  nan      nan    nan  nan
993621   nan   nan  nan  nan      nan    nan  nan
888961   nan   nan  nan  nan      nan    nan  nan
368964   nan   nan  nan  nan      nan    nan  nan
395392   nan   nan  nan  nan      nan    nan  nan
731403   nan   nan  nan  nan      nan    nan  nan
453355   nan   nan  nan  nan      nan    nan  nan
310821   nan   nan  nan  nan      nan    nan  nan
721072   nan   nan  nan  nan      nan    nan  nan
579413   nan   nan  nan  nan      nan    nan  nan
100098   nan   nan  nan  nan      nan    nan  nan
831453   nan   nan  nan  nan      nan    nan  nan
705303   nan   nan  nan  nan      nan    nan  nan
663380   nan   nan  nan  nan      nan    nan  nan
652832   nan   nan  nan  nan      nan    nan  nan
699981   nan   nan  nan  nan      nan    nan  nan
384970   nan   nan  nan  nan      nan    nan  nan
...      ...   ...  ...  ...      ...    ...  ...
852402   nan   nan  nan  nan      nan    nan  nan
1025432  nan   nan  nan  nan      nan    nan  nan
553162   nan   nan  nan  nan      nan    nan  nan
873287   nan   nan  nan  nan      nan    nan  nan
537269   nan   nan  nan  nan      nan    nan  nan
47404    nan   nan  nan  nan      nan    nan  nan
1035955  nan   nan  nan  nan      nan    nan  nan
15635    nan   nan  nan  nan      nan    nan  nan
263249   nan   nan  nan  nan      nan    nan  nan
157725   nan   nan  nan  nan      nan    nan  nan
237016   nan   nan  nan  nan      nan    nan  nan
820896   nan   nan  nan  nan      nan    nan  nan
358479   nan   nan  nan  nan      nan    nan  nan
967334   nan   nan  nan  nan      nan    nan  nan
962072   nan   nan  nan  nan      nan    nan  nan
173549   nan   nan  nan  nan      nan    nan  nan
358480   nan   nan  nan  nan      nan    nan  nan
73840    nan   nan  nan  nan      nan    nan  nan
741975   nan   nan  nan  nan      nan    nan  nan
820897   nan   nan  nan  nan      nan    nan  nan
479421   nan   nan  nan  nan      nan    nan  nan
658046   nan   nan  nan  nan      nan    nan  nan
568856   nan   nan  nan  nan      nan    nan  nan
168253   nan   nan  nan  nan      nan    nan  nan
5216     nan   nan  nan  nan      nan    nan  nan
411374   nan   nan  nan  nan      nan    nan  nan
20909    nan   nan  nan  nan      nan    nan  nan
768255   nan   nan  nan  nan      nan    nan  nan
568857   nan   nan  nan  nan      nan    nan  nan
183970   nan   nan  nan  nan      nan    nan  nan

[1048575 rows x 10 columns]

In [4]:
date_start =df["time"].min()
date_end = df["time"].max()
datetime_imput = [] 
date_start=pd.to_datetime(date_start)
date_end=pd.to_datetime(date_end)
i = date_start
j = date_end
while  i <= j:
    i = i + pd.Timedelta("1s")
    datetime_imput.append(i)
data_1 = pd.DataFrame(datetime_imput)
data_1["time1"]=data_1

In [6]:
dataframe1=data_1.merge(df, how = 'left',left_on='time1',right_on='time')
print(dataframe1['zxtyy'].value_counts())

Series([], Name: zxtyy, dtype: int64)